name: Build application
on:
  push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Graal JDK
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'graalvm'
        java-version: '25'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cache: 'maven'
    - name: Build image
      run: mvn -Pnative package
    - name: verify executable
      id: verify
      run: |
        ./certs.sh
        ./.github/scripts/verifyExecutable.sh
    - name: check log if error
      if: ${{ failure() && steps.verify.conclusion == 'failure' }}
      run: cat intercept.log
    - uses: actions/upload-artifact@v4
      with:
        path: target/https-intercept
        if-no-files-found: error
