name: Build application
on:
  push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Graal JDK
      uses: graalvm/setup-graalvm@v1
      with:
        distribution: 'graalvm'
        java-version: '21'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cache: 'maven'
    - name: Build image
      run: mvn -Pnative package
    - uses: actions/upload-artifact@v4
      with:
        path: target/https-intercept
        if-no-files-found: error
    - name: verify executable
      run: ./.github/scripts/verifyExecutable.sh
